version: "3.2"

networks:
  lifechamps_net:
    external:
      name: lifechamps_net

volumes:
  kafka_logs:

services:
  mqtt:
    build: mqtt
    container_name: mqtt_ca
    ports:
#      - "1883:1883"
      - "8883:8883"
    command: >
      bash -c "cp /etc/mosquitto/seq/ca.pem /etc/mosquitto/ca_certificate
      && chmod 664 /etc/mosquitto/ca_certificate/ca.pem
      && /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf"
    volumes:
      - ./mqtt/ca:/etc/mosquitto/ca_certificate
    networks:
      - lifechamps_net


  zoo:
    image: zookeeper:3.5
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    networks:
      - lifechamps_net

  kafka:
    image: wurstmeister/kafka:2.12-2.2.2
    container_name: kafka
    depends_on:
      - zoo
    environment: # outside will be removed latter, since all images will communicate from the same network
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - lifechamps_net
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    volumes:
      - kafka_logs:/kafka
      
  influxdb:
    image: influxdb:1.7.9
    container_name: influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=metrics
    networks:
      - lifechamps_net
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb      
